---
- name: Install MPI 
  include_role:
    name: openmpi
- name: Install other AMUSE prerequisites
  apt:
    update_cache: yes
    pkg:
      - libgsl-dev 
      - cmake 
      - libfftw3-3 
      - libfftw3-dev
      - libgmp3-dev 
      - libmpfr6
      - libmpfr-dev
      - libhdf5-serial-dev 
      - hdf5-tools
      - libblas-dev 
      - liblapack-dev
